name: Create Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Determine bump type from commits
        id: bump
        uses: actions/github-script@v7
        with:
          script: |
            const commits = context.payload.commits || [];

            const messages = commits.map(c => c.message);

            let bump = 'patch';

            if (messages.some(m => /^feat(\(.+\))?:/i.test(m))) {
              bump = 'minor';
            }

            if (messages.some(m => /!:/i.test(m))) {
              bump = 'major';
            }

            core.setOutput('bump', bump);

      - name: Bump version in package.json
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found"
            exit 1
          fi

          CURRENT=$(node -p "require('./package.json').version")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          case "${{ steps.bump.outputs.bump }}" in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            *)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW="$MAJOR.$MINOR.$PATCH"

          node -e "
            const fs = require('fs')
            const p = require('./package.json')
            p.version = '$NEW'
            fs.writeFileSync('package.json', JSON.stringify(p, null, 2) + '\n')
          "

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m "chore(release): bump version to v$NEW"
          git push origin main
