### Esto no es reusable - debe ir por proyecto
name: Delete Branch After Tag

on:
  workflow_run:
    workflows: ["Create Tag"]
    types: [completed]

jobs:
  delete-branch:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
