name: Workflow PR

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      pnpm-version:
        type: string
        default: '11.1.2'

permissions:
  contents: read
  pull-requests: write

jobs:
  security:
    name: Security
    uses: ./.github/workflows/frontend-security-scan.yml
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  load-values:
    name: Load Values
    needs: security
    uses: ./.github/workflows/frontend-pr-load-values.yml
    with:
      node-version: ${{ inputs.node-version }}

  unit-test:
    name: Unit Tests
    needs: load-values
    uses: ./.github/workflows/frontend-pr-unit-test.yml
    with:
      node-version: ${{ inputs.node-version }}

  validate-tag:
    name: Validate Tag
    needs: unit-test
    uses: ./.github/workflows/frontend-pr-validate-tag.yml
